---
kind: pipeline
type: docker
name: compose
platform:
  os: linux
  arch: arm64
steps:
  - name: delete compose services
    image: kameshsampath/kube-dev-tools:v0.0.4
    commands:
      - cd docker
      - docker-compose down --remove-orphans --rmi=all || true
    volumes:
      # helps connecting to drone
      - name: dockersock
        path: /var/run/docker.sock
volumes:
  # helps connecting to drone
  - name: dockersock
    host:
      path: /var/run/docker.sock
---
kind: pipeline
type: docker
name: k8s
platform:
  os: linux
  arch: arm64
steps:
  - name: k8s-undeploy
    image: kameshsampath/kube-dev-tools:v0.0.4
    pull: if-not-present
    commands:
      - kind get kubeconfig --internal --name=$KIND_CLUSTER_NAME > /apps/.kube/config
      - kubectl config use-context $KUBECTL_CONTEXT
      - kubectl config set-context --current --namespace=$APPS_NAMESPACE
      - kustomize build /drone/src/k8s | envsubst | kubectl delete -f -
    volumes:
      - name: dockersock
        path: /var/run/docker.sock
  - name: delete kind cluster
    image: kameshsampath/kube-dev-tools:v0.0.4
    commands:
      - kind delete cluster --name=$KIND_CLUSTER_NAME || true
      - docker rm --force kind-registry || true
      - docker network rm $DOCKER_NETWORK || true
    volumes:
      # helps connecting to drone
      - name: dockersock
        path: /var/run/docker.sock
volumes:
  # helps connecting to drone
  - name: dockersock
    host:
      path: /var/run/docker.sock
## TODO add google cloud cleanup
