---
kind: pipeline
type: docker
name: clean-compose-services
platform:
  os: linux
  arch: arm64
steps:
  - name: delete compose services
    image: kameshsampath/kube-dev-tools:v0.0.4
    commands:
      - cd docker
      - docker-compose down --remove-orphans --rmi=all || true
    volumes:
      # helps connecting to drone
      - name: dockersock
        path: /var/run/docker.sock
volumes:
  # helps connecting to drone
  - name: dockersock
    host:
      path: /var/run/docker.sock
---
kind: pipeline
type: docker
name: clean-kind
platform:
  os: linux
  arch: arm64
steps:
  - name: delete kind cluster
    image: kameshsampath/kube-dev-tools:v0.0.4
    commands:
      - kind delete cluster --name=$KIND_CLUSTER_NAME || true
      - docker rm --force kind-registry || true
      - docker network rm $DOCKER_NETWORK || true
    volumes:
      # helps connecting to drone
      - name: dockersock
        path: /var/run/docker.sock
volumes:
  # helps connecting to drone
  - name: dockersock
    host:
      path: /var/run/docker.sock
---
## TODO add google cloud cleanup
