no-duplicate-header:
  allow_different_nesting: true
  siblings_only: true
line-length:
  line_length: 120
  heading_line_length: 120
  code_block_line_length: 120
  code_blocks: true
  tables: true
  headings: true
  headers: true
  strict: false
  stern: true
