namespace: fruits-app

generatorOptions:
  disableNameSuffixHash: true

commonLabels:
  app: fruits-app-ui
  version: v1.0

configMapGenerator:
  - name: ui-config
    files:
      - .env
resources:
- sa.yaml
- deployment.yaml
- service.yaml
